import type { NextPage } from 'next'
import Head from 'next/head'
import Image from 'next/image'
import PrimaryLayout from '../components/layouts/primary/PrimaryLayout'
import styles from '../styles/Home.module.css'
import { NextPageWithLayout } from './page'

const Home: NextPageWithLayout = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a href="http://focaltiles.com/">FocalTiles!</a>
        </h1>
      </main>
    </div>
  )
}

Home.getLayout = (page) => {
  return (
    <PrimaryLayout>
      {page}
    </PrimaryLayout>
  )
}

export default Home