import Head from 'next/head'
import Link from 'next/link'
import PrimaryLayout from '../components/layouts/primary/PrimaryLayout'
import styles from '../styles/Home.module.css'
import { NextPageWithLayout } from './page'
import Button from '../components/inputs/button/Button'

const Home: NextPageWithLayout = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className={styles.main}>
        <h1 className={styles.title}>
          Welcome to <a className={'hover:decoration-primary-400 hover:underline focus:decoration-primary-400 focus:underline active:decoration-primary-400 active:underline'} href="http://focaltiles.com/focalapp"><span className={'text-primary-400'}>FocalTiles!</span></a>
        </h1>
        <Link href={'/focalapp'}>
          <a>
            <Button text={'Go to App'}/>
          </a>
        </Link>
      </main>
    </div>
  )
}

Home.getLayout = (page) => {
  return (
    <PrimaryLayout>
      {page}
    </PrimaryLayout>
  )
}

export default Home